### PR TITLE
Use XSLoader

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by toddr** [comment]
We patch String::CRC32 to use the lighter XSLoader in our perl. We're including the patch in case you want to use it.

**Comment by leejo** [comment]
Looks good, thanks @atoomic and @toddr - what's the reason to favour XSLoader over DynaLoader? (So I can include this in the commit message). Also, do you think this will go anyway towards fixing #4 ?

**Comment by atoomic** [comment]
@leejo the main reason is to reduce memory footprint and avoid the unneeded complexity of DynaLoader
IMO this is not related at all with #4

**Comment by leejo** [comment]
Alright! No worries. I shall get this merged and uploaded to CPAN on Monday. Thanks again 👍

**Pull request merged**
